# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masculinitive1', models.CharField(max_length=50)),
                ('feminitive1', models.CharField(max_length=50)),
                ('SYM1', models.BooleanField(default=False)),
                ('link1', models.SlugField(allow_unicode=True, max_length=200)),
                ('plural1', models.CharField(max_length=50)),
                ('rodovy1', models.CharField(max_length=50)),
                ('davalny1', models.CharField(max_length=50)),
                ('znahidny1', models.CharField(max_length=50)),
                ('orudny1', models.CharField(max_length=50)),
                ('miscevy1', models.CharField(max_length=50)),
                ('klychny1', models.CharField(max_length=50)),
                ('def_sym1', models.CharField(max_length=5000)),
                ('def_our1', models.CharField(max_length=5000)),
                ('usage1', models.CharField(max_length=10000)),
            ],
        ),
    ]
